### ISSUE TITLE
Missing Installation instructions

### ISSUE THREAD

**Issue by owensy** [SvenSommer/MMM-GoogleAnalytics#1]
I've been waiting ages for someone with the skill to create this exact module so thank you very much!

I've got this setup and working on my MagicMirror now but I noticed a couple steps missing in the installation instructions.

You need to perform an npm install for NodeGeocoder, and you also need to enable to google analytics api which isn't mentioned on the robstechlog blog post.

Hope that helps

**Comment by SvenSommer** [comment]
Hey owensy,
I'm glad you like it. Please feel free to send me your experiences and suggestion for improvement.

I could add the `npm install node-geocoder` information in Readme.  

But can you please describe exactly where you had to enable the google analytics api?

**Please note**: The current update includes some two new parameters (_showtotalline, debug_) and is requiring an updated version of your entry in the _config.js_ file, caused by changing the variable types.

Thank you for sharing!

**Comment by owensy** [comment]
The API is enabled in the google developers console, after you do all the instructions mentioned in robstechlog, if you click on library you can search for the api's, I enabled two as I wasn't sure which one, they are Analytics API and Google Analytics Reporting API.

I seem to have an issue with mine where it won't refresh however, it grabs the stats on first load but nothing after, I don't know if I'm missing any dependency?

Other than that, I was going to suggest a way to remove the totals line, but looks like you were way ahead of me! :)

Thanks again Sven!

**Comment by SvenSommer** [comment]
Hey thank you for your reporting and improving!

The refreshing issue should be solved and the optional total line available, when you update to new newest version.

Just do a 'git pull' in your MMM-GoogleAnalytics folder and don't forget to update your config.js entry also!!

Have a nice day!

**Comment by owensy** [comment]
Thanks, works a treat now
